package_managers:
  darwin:  # macOS
    - name: brew
      check_cmd: brew -v

  windows:
    - name: choco
      check_cmd: choco -v
    - name: scoop
      check_cmd: scoop --version
    - name: winget
      check_cmd: winget -v

  linux:
    - name: apt
      check_cmd: apt --version
    - name: pacman
      check_cmd: pacman --version
    - name: yay
      check_cmd: yay --version

programs:

  yay:
    description: "Yet Another Yogurt - An AUR Helper Written in Go"
    tags: ["yay(install stand-alone)"]
    installs:
      linux:
        pacman: >
          sudo pacman -S --needed git base-devel &&
          git clone https://aur.archlinux.org/yay.git &&
          cd yay &&
          makepkg -si

  git:
    description: "Git Version Control System"
    tags: ["version control"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y git
        pacman: >
          sudo pacman -Syu --needed git
      darwin:
        brew: >
          brew install git || brew upgrade git
      windows:
        winget: >
          winget install --id Git.Git --silent --scope machine

  go:
    description: "Go Programming Language"
    tags: ["development", "language"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y golang
        pacman: >
          sudo pacman -Syu --needed go
      darwin:
        brew: >
          brew install go || brew upgrade go
      windows:
        winget: >
          winget install --id golang.go --silent --scope machine

  google-chrome:
    description: "Google Chrome Web Browser"
    tags: ["browser"]
    installs:
      linux:
        apt: >
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub |
          gpg --dearmor > /usr/share/keyrings/google-chrome-archive-keyring.gpg &&
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list &&
          sudo apt update &&
          sudo apt install -y google-chrome-stable
        yay: >
          yay -S --needed google-chrome
      darwin:
        brew: >
          brew install google-chrome || brew upgrade google-chrome
      windows:
        winget: >
          winget install --id Google.Chrome --silent --scope machine

  firefox:
    description: "Mozilla Firefox Web Browser"
    tags: ["browser"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y firefox
        pacman: >
          sudo pacman -Syu --needed firefox
      darwin:
        brew: >
          brew install firefox || brew upgrade firefox
      windows:
        winget: >
          winget install --id Mozilla.Firefox --silent --scope machine

  neovim:
    description: "Neovim Text Editor"
    tags: ["editor", "development"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y neovim
        pacman: >
          sudo pacman -Syu --needed neovim
      darwin:
        brew: >
          brew install neovim || brew upgrade neovim
      windows:
        winget: >
          winget install --id Neovim.Neovim --silent --scope machine

  vscode:
    description: "Visual Studio Code"
    tags: ["editor", "development"]
    installs:
      linux:
        apt: >
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor > packages.microsoft.gpg &&
          sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/ &&
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list' &&
          sudo apt update &&
          sudo apt install -y code
        pacman: >
          sudo pacman -Syu --needed code
      darwin:
        brew: >
          brew install --cask visual-studio-code || brew upgrade --cask visual-studio-code
      windows:
        winget: >
          winget install --id Microsoft.VisualStudioCode --silent --scope machine

  tree:
    description: "Tree Command to display directories"
    tags: ["utility"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y tree
        pacman: >
          sudo pacman -Syu --needed tree
      darwin:
        brew: >
          brew install tree || brew upgrade tree
      windows:
        winget: >
          winget install --id gnuwin32.tree --silent --scope machine

  neofetch:
    description: "Neofetch system info tool"
    tags: ["utility"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y neofetch
        pacman: >
          sudo pacman -Syu --needed neofetch
      darwin:
        brew: >
          brew install neofetch || brew upgrade neofetch
      windows:
        winget: >
          winget install --id neofetch --silent --scope machine

  fzf:
    description: "fzf - A command-line fuzzy finder"
    tags: ["utility", "search"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y fzf
        pacman: >
          sudo pacman -Syu --needed fzf
      darwin:
        brew: >
          brew install fzf || brew upgrade fzf
      windows:
        winget: >
          winget install --id fzf --silent --scope machine

  yazi:
    description: "yazi - A blazing fast terminal file manager"
    tags: ["utility", "file manager"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y yazi
        yay: >
          yay -S --needed yazi
      darwin:
        brew: >
          brew install yazi || brew upgrade yazi
      windows:
        winget: >
          winget install --id yazi --silent --scope machine

  gh:
    description: "GitHub CLI"
    tags: ["utility", "development"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y gh
        pacman: >
          sudo pacman -Syu --needed gh
      darwin:
        brew: >
          brew install gh || brew upgrade gh
      windows:
        winget: >
          winget install --id GitHub.cli --silent --scope machine