package_managers:
  darwin:  # macOS
    - name: brew
      check_cmd: brew -v

  windows:
    - name: choco
      check_cmd: choco -v
    - name: scoop
      check_cmd: scoop --version
    - name: winget
      check_cmd: winget -v

  linux:
    - name: apt
      check_cmd: apt --version
    - name: pacman
      check_cmd: pacman --version
    - name: yay
      check_cmd: yay --version

programs:

  yay:
    description: "Yet Another Yogurt - An AUR Helper Written in Go"
    tags: ["yay(install stand-alone)"]
    installs:
      linux:
        pacman: >
          sudo pacman -S --needed git base-devel &&
          git clone https://aur.archlinux.org/yay.git &&
          cd yay &&
          makepkg -si

  git:
    description: "Git Version Control System"
    tags: ["version control"]
    installs:
      linux:
        apt: >
          sudo apt update &&
          sudo apt install -y git
        pacman: >
          sudo pacman -Syu --needed git
      darwin:
        brew: >
          brew install git || brew upgrade git
      windows:
        winget: >
          winget install --id Git.Git --silent --scope machine